name: dart
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'
  
dependencies:
  http: ^0.13.4
  path: ^1.8.1
  uuid: ^3.0.6
  process_run: ^0.12.2+2
  quill_markdown: 
    path: quill_markdown/

dev_dependencies:
  lints: ^1.0.0
