name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install coscli
        run: |
          wget https://github.com/tencentyun/coscli/releases/download/v0.11.0-beta/coscli-linux
          mv coscli-linux coscli
          chmod 755 coscli
          ./coscli --version
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.3
      - name: run dart scripts
        shell: bash
        env: 
          cossecretid: ${{ secrets.cossecretid }}
          cossecretkey: ${{ secrets.cossecretkey }}
        run: |
          cd ${{ github.workspace }}/scripts/dart
          dart pub get
          ls
          dart bin/main.dart -i $cossecretkey -k $cossecretkey
      - name: Commit files
        run: |
          git config --local user.email "ybz975218925@live.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.my_github_token }}
          branch: ${{ github.ref }}